#!/usr/bin/env python3
"""
组装 references.bib：对每篇论文，优先用 bibtex-cache.bib 里的**权威**条目（arXiv/Crossref），
缺失则从 frontmatter 字段**无幻觉重建**。citation key 一律用 frontmatter 里 pinned 的 cite_key。

依赖：先跑 build_paper_index.py（生成 paper_index.json）+ fetch_bibtex.py（填 cache）。
覆盖旧 references.bib 前会自动备份到 references.bib.bak。
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

import fetch_bibtex as fb

PROJECT_ROOT = Path(__file__).resolve().parents[3]
INDEX_FILE = Path(__file__).resolve().parent / "paper_index.json"
CACHE_FILE = PROJECT_ROOT / "references" / "bibtex-cache.bib"
OUTPUT_FILE = PROJECT_ROOT / "references.bib"


def index_entry_to_fm(p: dict) -> dict:
    """把 paper_index 条目转成 reconstruct_bibtex 期望的 frontmatter dict。"""
    return {
        "title": p.get("title", ""),
        "authors": p.get("authors", []),
        "date_publish": p.get("year", ""),
        "venue": p.get("venue", ""),
        "arxiv_id": p.get("arxiv_id", ""),
        "doi": p.get("doi", ""),
        "url": p.get("url", ""),
    }


def main() -> int:
    if not INDEX_FILE.exists():
        print("Error: paper_index.json 不存在，请先跑 build_paper_index.py")
        return 1
    papers = json.loads(INDEX_FILE.read_text(encoding="utf-8"))
    cache = fb.parse_cache(CACHE_FILE.read_text(encoding="utf-8")) if CACHE_FILE.exists() else {}

    entries: list[str] = []
    seen: set[str] = set()
    stats = {"canonical": 0, "reconstructed": 0, "skipped_no_key": 0, "dup_key": 0}

    for p in papers:
        key = p.get("cite_key", "").strip()
        if not key:
            stats["skipped_no_key"] += 1
            continue
        if key in seen:
            stats["dup_key"] += 1
            continue
        seen.add(key)

        cached = cache.get(key)
        if cached:
            entries.append(cached["bibtex"].strip())
            if cached["source"] in ("arxiv", "crossref"):
                stats["canonical"] += 1
            else:
                stats["reconstructed"] += 1
        else:
            entries.append(fb.reconstruct_bibtex(index_entry_to_fm(p), key))
            stats["reconstructed"] += 1

    # 备份旧文件
    if OUTPUT_FILE.exists():
        shutil.copy2(OUTPUT_FILE, OUTPUT_FILE.with_suffix(".bib.bak"))

    header = (
        "% references.bib — generated by ReadPaperMachine latex-citation-enhancer\n"
        f"% {len(entries)} entries | canonical(arxiv/crossref)={stats['canonical']} "
        f"reconstructed={stats['reconstructed']}\n"
        "% 权威条目来自 references/bibtex-cache.bib；citation key = frontmatter 的 cite_key。\n\n"
    )
    OUTPUT_FILE.write_text(header + "\n\n".join(entries) + "\n", encoding="utf-8")

    print(f"✅ {OUTPUT_FILE.name}: {len(entries)} entries "
          f"(canonical={stats['canonical']}, reconstructed={stats['reconstructed']})")
    if stats["skipped_no_key"]:
        print(f"   skipped (no cite_key): {stats['skipped_no_key']}")
    if stats["dup_key"]:
        print(f"   ⚠ duplicate cite_key skipped: {stats['dup_key']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
